// <auto-generated />
namespace NewsReader.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class With_seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(With_seed));
        
        string IMigrationMetadata.Id
        {
            get { return "201908050524026_With_seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
